# Generated by Django 4.1.4 on 2022-12-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('libro', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
            ],
        ),
    ]
