# Generated by Django 4.1.4 on 2022-12-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discoteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('disco', models.CharField(max_length=50)),
                ('cantidad_canciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videoteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('fecha_estreno', models.DateField(blank=True)),
            ],
        ),
    ]
